services:
  vllm-server:
    image: vllm/vllm-openai:nightly
    container_name: vllm-server
    command: --model allenai/olmOCR-7B-0825-FP8 --host 0.0.0.0 --port 8001 --served-model-name olmocr --max-model-len 16384 --gpu-memory-utilization 0.90 --max-num-batched-tokens 32768 --max-num-seqs 128 --tensor-parallel-size 1 --block-size 16 --swap-space 8 --max-parallel-loading-workers 2 --disable-log-stats --disable-custom-all-reduce
    ports:
      - "8001:8001"
    volumes:
      - ./model_cache:/root/.cache/huggingface
      - /mnt/hf_models:/mnt/hf_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLMOCR_DEVICE=cuda

  olmocr-api:
    build: .
    container_name: olmocr-api
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/workspace
    depends_on:
      - vllm-server
    environment:
      - OLMOCR_DEVICE=cuda

volumes:
  model_cache:
    driver: local
